#!/usr/bin/env python3
"""
Generating what gets installed on the remote host.

Everything the remote runs is written here and pushed from here. Nothing is
edited by hand on that machine, which is what lets `status` answer "is what is
installed still what we would install now?" instead of only "is it running?".

That question is answered with a fingerprint embedded in the generated
configuration: a hash of the values it was built from. Reading one line back
tells us whether the two have drifted, without reading the file that holds the
password.

SECURITY: the access rule is the whole point of the generated configuration.
- Restricted mode names exactly one address. rsync denies everything that does
  not match an entry in `hosts allow`, so naming one address IS deny-by-default;
  there is no second rule to keep in step with it.
- Every library is published read only. Nothing can be written, replaced or
  removed through this channel whatever else goes wrong.
- Libraries are not listable, so a port scan learns that something is there but
  nothing about what.
"""

import hashlib
import posixpath
from typing import List, Optional, Tuple

from . import layout

#: Bumped when the generated shape changes in a way that needs a reinstall.
#: It is part of the fingerprint, so an installation generated by an older
#: version reports as out of date rather than silently staying as it was.
TEMPLATE_VERSION = '1'

ACCESS_RESTRICTED = 'restricted'
ACCESS_PASSWORD_ONLY = 'password'

#: More than one library can be pulled at a time, and a stuck connection should
#: not lock out the next transfer. Well above the queue's own limit.
MAX_CONNECTIONS = 8


def fingerprint(port: int, access_mode: str, allowed_address: str,
                roots: List[Tuple[str, str]]) -> str:
    """
    A short hash of everything the generated configuration depends on.

    The password is deliberately NOT part of it. Rotating the password rewrites
    the password file and restarts the service; it does not change what the
    configuration says, and reporting the installation as out of date because a
    secret was rotated would train an operator to ignore the warning.
    """
    material = '|'.join([
        TEMPLATE_VERSION,
        str(port),
        access_mode,
        allowed_address or '',
        ';'.join(f"{name}={root}" for name, root in roots),
    ])
    return hashlib.sha256(material.encode('utf-8')).hexdigest()[:16]


def render_conf(home: str, port: int, access_mode: str, allowed_address: str,
                roots: List[Tuple[str, str]]) -> str:
    """The rsync daemon configuration."""
    lines = [
        '# Generated by DragonCP. Do not edit by hand — it is overwritten on',
        '# every install, and hand edits make the status check lie.',
        f"# dragoncp-fingerprint: {fingerprint(port, access_mode, allowed_address, roots)}",
        '',
        f"port = {port}",
        f"pid file = {layout.pid_path(home)}",
        f"lock file = {layout.lock_path(home)}",
        f"log file = {layout.log_path(home)}",
        '',
        '# chroot needs root, which this account does not have. Every published',
        '# path is absolute and read only, and none of them is the home',
        '# directory, so there is nothing here to escape into.',
        'use chroot = no',
        f"max connections = {MAX_CONNECTIONS}",
        'reverse lookup = no',
        '',
    ]

    if access_mode == ACCESS_RESTRICTED and allowed_address:
        lines += [
            '# Naming an address here refuses every other address by default.',
            f"hosts allow = {allowed_address}",
            '',
        ]
    else:
        lines += [
            '# PASSWORD ONLY: any address may connect and is held off by the',
            '# password alone. This is the deliberate fallback for a changed or',
            '# lost fixed address, not the normal setting.',
            '',
        ]

    for name, root in roots:
        lines += [
            f"[{name}]",
            f"    path = {root}",
            '    read only = yes',
            '    list = no',
            f"    auth users = {layout.DAEMON_USER}",
            f"    secrets file = {layout.secrets_path(home)}",
            '',
        ]

    return '\n'.join(lines) + '\n'


def render_secrets(password: str) -> str:
    """The daemon's password file. Written owner-only; rsync refuses it otherwise."""
    return f"{layout.DAEMON_USER}:{password}\n"


def render_unit(home: str, rsync_binary: str, port: int) -> str:
    """
    The service definition.

    `--no-detach` is what makes this a service systemd can actually supervise;
    without it rsync forks away and systemd watches a process that has already
    exited. `Restart=always` covers a crash, and `WantedBy=default.target` plus
    the account's existing permission to keep services after logout covers a
    reboot. That combination is the "something that keeps it running" — written
    by the machine that already does this for every other application on that
    host, rather than by us.
    """
    conf = layout.conf_path(home)
    return '\n'.join([
        '# Generated by DragonCP. Do not edit by hand.',
        '[Unit]',
        'Description=DragonCP transfer server (rsync daemon)',
        'After=network-online.target',
        '',
        '[Service]',
        'Type=simple',
        f"ExecStart={rsync_binary} --daemon --no-detach --config={conf} --port={port}",
        'Restart=always',
        'RestartSec=5',
        '',
        '[Install]',
        'WantedBy=default.target',
        '',
    ])


def installed_fingerprint(conf_text: Optional[str]) -> Optional[str]:
    """Read the fingerprint back out of an installed configuration."""
    if not conf_text:
        return None
    for line in conf_text.splitlines():
        marker = '# dragoncp-fingerprint:'
        if line.startswith(marker):
            return line[len(marker):].strip() or None
    return None
